// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEItemKeys
    {
        public static string Level_Level1 = "Level1";
        public static string Level_Level2 = "Level2";
        public static string Task_Task1_3 = "Task1_3";
        public static string Task_Task1_2 = "Task1_2";
        public static string Task_Task1_1 = "Task1_1";
        public static string Task_Task2_1 = "Task2_1";
        public static string Task_Task2_2 = "Task2_2";
        public static string Task_Task2_3 = "Task2_3";
        public static string Task_Task2_4 = "Task2_4";
        public static string EnemyAttr_EnemyAttr_1_1 = "EnemyAttr_1_1";
        public static string EnemyAttr_EnemyAttr_1_2 = "EnemyAttr_1_2";
        public static string EnemyAttr_EnemyAttr_1_3 = "EnemyAttr_1_3";
        public static string EnemyAttr_EnemyAttr_1_4 = "EnemyAttr_1_4";
        public static string EnemyAttr_EnemyAttr_1_5 = "EnemyAttr_1_5";
        public static string EnemyAttr_EnemyAttr_1_6 = "EnemyAttr_1_6";
        public static string EnemyAttr_EnemyAttr_1_7 = "EnemyAttr_1_7";
        public static string EnemyAttr_EnemyAttr_1_8 = "EnemyAttr_1_8";
        public static string WaveItem_Task_1_1_Wave_1_Item_1 = "Task_1_1_Wave_1_Item_1";
        public static string WaveItem_Task_1_1_Wave_1_Item_1_919df013861c47b29104e39a5b26e0a1 = "Task_1_1_Wave_1_Item_1_919df013861c47b29104e39a5b26e0a1";
        public static string Wave_Task_1_1_Wave_1 = "Task_1_1_Wave_1";
        public static string TaskInfo_Task_1_1 = "Task_1_1";
        public static string Medical_MedicalBox = "MedicalBox";
        public static string Weapon_AK47 = "AK47";
        public static string Weapon_Gun = "Gun";
        public static string Bomb_Bomb = "Bomb";
        public static string Bomb_Bomb_236755f9f77d474d9cc698abccce557c = "Bomb_236755f9f77d474d9cc698abccce557c";
    }
}
