// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEItemKeys
    {
        public static string WeaponLevel_w1_lv3 = "w1_lv3";
        public static string WeaponLevel_w1_lv2 = "w1_lv2";
        public static string WeaponLevel_w1_lv1 = "w1_lv1";
        public static string Medical_MedicalBox = "MedicalBox";
        public static string Weapon_MP5 = "MP5";
        public static string Weapon_AK47 = "AK47";
        public static string Bomb_Bomb = "Bomb";
        public static string Zombie_Zombie_Fat = "Zombie_Fat";
        public static string Zombie_Zombie_FeMale = "Zombie_FeMale";
        public static string Zombie_Zombie_Male = "Zombie_Male";
        public static string Zombie_Zombie_Male_2ad89c59d35445e1a48f6880093ad4ae = "Zombie_Male_2ad89c59d35445e1a48f6880093ad4ae";
        public static string MissionRecord_Mission_1_1 = "Mission_1_1";
        public static string MissionRecord_Mission_1_1_0b4578c1fc474553b6d4ca57813f674d = "Mission_1_1_0b4578c1fc474553b6d4ca57813f674d";
        public static string MissionRecord_Mission_1_1_0b4578c1fc474553b6d4ca57813f674d_b8b5755ba56f4134a33bbdf85ad95c1b = "Mission_1_1_0b4578c1fc474553b6d4ca57813f674d_b8b5755ba56f4134a33bbdf85ad95c1b";
        public static string MissionRecord_Mission_1_1_0b4578c1fc474553b6d4ca57813f674d_b8b5755ba56f4134a33bbdf85ad95c1b_97d62b40934e4ee2a3f9c31f3f3e1642 = "Mission_1_1_0b4578c1fc474553b6d4ca57813f674d_b8b5755ba56f4134a33bbdf85ad95c1b_97d62b40934e4ee2a3f9c31f3f3e1642";
        public static string MissionRecord_Mission_1_1_0b4578c1fc474553b6d4ca57813f674d_b8b5755ba56f4134a33bbdf85ad95c1b_97d62b40934e4ee2a3f9c31f3f3e1642_05c17d3a15d44aee858e8f4539514611 = "Mission_1_1_0b4578c1fc474553b6d4ca57813f674d_b8b5755ba56f4134a33bbdf85ad95c1b_97d62b40934e4ee2a3f9c31f3f3e1642_05c17d3a15d44aee858e8f4539514611";
    }
}
