// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDELevelData : IGDEData
    {
        private static string LevelNum1Key = "LevelNum1";
		private int _LevelNum1;
        public int LevelNum1
        {
            get { return _LevelNum1; }
            set {
                if (_LevelNum1 != value)
                {
                    _LevelNum1 = value;
                    GDEDataManager.SetInt(_key+"_"+LevelNum1Key, _LevelNum1);
                }
            }
        }

        private static string LevelNameKey = "LevelName";
		private string _LevelName;
        public string LevelName
        {
            get { return _LevelName; }
            set {
                if (_LevelName != value)
                {
                    _LevelName = value;
                    GDEDataManager.SetString(_key+"_"+LevelNameKey, _LevelName);
                }
            }
        }

        private static string TaskListKey = "TaskList";
		public List<GDETaskData>      TaskList;
		public void Set_TaskList()
        {
	        GDEDataManager.SetCustomList(_key+"_"+TaskListKey, TaskList);
		}
		

        public GDELevelData()
		{
			_key = string.Empty;
		}

		public GDELevelData(string key)
		{
			_key = key;
		}
		
        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetInt(LevelNum1Key, out _LevelNum1);
                dict.TryGetString(LevelNameKey, out _LevelName);

                dict.TryGetCustomList(TaskListKey, out TaskList);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _LevelNum1 = GDEDataManager.GetInt(_key+"_"+LevelNum1Key, _LevelNum1);
            _LevelName = GDEDataManager.GetString(_key+"_"+LevelNameKey, _LevelName);

            TaskList = GDEDataManager.GetCustomList(_key+"_"+TaskListKey, TaskList);
         }

        public void Reset_LevelNum1()
        {
            GDEDataManager.ResetToDefault(_key, LevelNum1Key);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(LevelNum1Key, out _LevelNum1);
        }

        public void Reset_LevelName()
        {
            GDEDataManager.ResetToDefault(_key, LevelNameKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(LevelNameKey, out _LevelName);
        }

        public void Reset_TaskList()
		{
			GDEDataManager.ResetToDefault(_key, TaskListKey);

			Dictionary<string, object> dict;
			GDEDataManager.Get(_key, out dict);

			dict.TryGetCustomList(TaskListKey, out TaskList);
			TaskList = GDEDataManager.GetCustomList(_key+"_"+TaskListKey, TaskList);

			TaskList.ForEach(x => x.ResetAll());
		}

        public void ResetAll()
        {
            GDEDataManager.ResetToDefault(_key, LevelNameKey);
            GDEDataManager.ResetToDefault(_key, TaskListKey);
            GDEDataManager.ResetToDefault(_key, LevelNum1Key);

            Reset_TaskList();

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
