// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEMissionRecordData : IGDEData
    {
        private static string IDKey = "ID";
		private int _ID;
        public int ID
        {
            get { return _ID; }
            set {
                if (_ID != value)
                {
                    _ID = value;
                    GDEDataManager.SetInt(_key+"_"+IDKey, _ID);
                }
            }
        }

        private static string MissionIDKey = "MissionID";
		private int _MissionID;
        public int MissionID
        {
            get { return _MissionID; }
            set {
                if (_MissionID != value)
                {
                    _MissionID = value;
                    GDEDataManager.SetInt(_key+"_"+MissionIDKey, _MissionID);
                }
            }
        }

        private static string WaveKey = "Wave";
		private int _Wave;
        public int Wave
        {
            get { return _Wave; }
            set {
                if (_Wave != value)
                {
                    _Wave = value;
                    GDEDataManager.SetInt(_key+"_"+WaveKey, _Wave);
                }
            }
        }

        private static string AlertKey = "Alert";
		private int _Alert;
        public int Alert
        {
            get { return _Alert; }
            set {
                if (_Alert != value)
                {
                    _Alert = value;
                    GDEDataManager.SetInt(_key+"_"+AlertKey, _Alert);
                }
            }
        }

        private static string IDZombieKey = "IDZombie";
		private int _IDZombie;
        public int IDZombie
        {
            get { return _IDZombie; }
            set {
                if (_IDZombie != value)
                {
                    _IDZombie = value;
                    GDEDataManager.SetInt(_key+"_"+IDZombieKey, _IDZombie);
                }
            }
        }

        private static string NumberKey = "Number";
		private int _Number;
        public int Number
        {
            get { return _Number; }
            set {
                if (_Number != value)
                {
                    _Number = value;
                    GDEDataManager.SetInt(_key+"_"+NumberKey, _Number);
                }
            }
        }

        private static string PositionKey = "Position";
		private int _Position;
        public int Position
        {
            get { return _Position; }
            set {
                if (_Position != value)
                {
                    _Position = value;
                    GDEDataManager.SetInt(_key+"_"+PositionKey, _Position);
                }
            }
        }

        private static string SpeedKey = "Speed";
		private int _Speed;
        public int Speed
        {
            get { return _Speed; }
            set {
                if (_Speed != value)
                {
                    _Speed = value;
                    GDEDataManager.SetInt(_key+"_"+SpeedKey, _Speed);
                }
            }
        }

        private static string TimeWaitingSpwanKey = "TimeWaitingSpwan";
		private int _TimeWaitingSpwan;
        public int TimeWaitingSpwan
        {
            get { return _TimeWaitingSpwan; }
            set {
                if (_TimeWaitingSpwan != value)
                {
                    _TimeWaitingSpwan = value;
                    GDEDataManager.SetInt(_key+"_"+TimeWaitingSpwanKey, _TimeWaitingSpwan);
                }
            }
        }

        private static string MaxZombiesKey = "MaxZombies";
		private int _MaxZombies;
        public int MaxZombies
        {
            get { return _MaxZombies; }
            set {
                if (_MaxZombies != value)
                {
                    _MaxZombies = value;
                    GDEDataManager.SetInt(_key+"_"+MaxZombiesKey, _MaxZombies);
                }
            }
        }

        public GDEMissionRecordData()
		{
			_key = string.Empty;
		}

		public GDEMissionRecordData(string key)
		{
			_key = key;
		}
		
        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetInt(IDKey, out _ID);
                dict.TryGetInt(MissionIDKey, out _MissionID);
                dict.TryGetInt(WaveKey, out _Wave);
                dict.TryGetInt(AlertKey, out _Alert);
                dict.TryGetInt(IDZombieKey, out _IDZombie);
                dict.TryGetInt(NumberKey, out _Number);
                dict.TryGetInt(PositionKey, out _Position);
                dict.TryGetInt(SpeedKey, out _Speed);
                dict.TryGetInt(TimeWaitingSpwanKey, out _TimeWaitingSpwan);
                dict.TryGetInt(MaxZombiesKey, out _MaxZombies);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _ID = GDEDataManager.GetInt(_key+"_"+IDKey, _ID);
            _MissionID = GDEDataManager.GetInt(_key+"_"+MissionIDKey, _MissionID);
            _Wave = GDEDataManager.GetInt(_key+"_"+WaveKey, _Wave);
            _Alert = GDEDataManager.GetInt(_key+"_"+AlertKey, _Alert);
            _IDZombie = GDEDataManager.GetInt(_key+"_"+IDZombieKey, _IDZombie);
            _Number = GDEDataManager.GetInt(_key+"_"+NumberKey, _Number);
            _Position = GDEDataManager.GetInt(_key+"_"+PositionKey, _Position);
            _Speed = GDEDataManager.GetInt(_key+"_"+SpeedKey, _Speed);
            _TimeWaitingSpwan = GDEDataManager.GetInt(_key+"_"+TimeWaitingSpwanKey, _TimeWaitingSpwan);
            _MaxZombies = GDEDataManager.GetInt(_key+"_"+MaxZombiesKey, _MaxZombies);
         }

        public void Reset_ID()
        {
            GDEDataManager.ResetToDefault(_key, IDKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(IDKey, out _ID);
        }

        public void Reset_MissionID()
        {
            GDEDataManager.ResetToDefault(_key, MissionIDKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(MissionIDKey, out _MissionID);
        }

        public void Reset_Wave()
        {
            GDEDataManager.ResetToDefault(_key, WaveKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(WaveKey, out _Wave);
        }

        public void Reset_Alert()
        {
            GDEDataManager.ResetToDefault(_key, AlertKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(AlertKey, out _Alert);
        }

        public void Reset_IDZombie()
        {
            GDEDataManager.ResetToDefault(_key, IDZombieKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(IDZombieKey, out _IDZombie);
        }

        public void Reset_Number()
        {
            GDEDataManager.ResetToDefault(_key, NumberKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(NumberKey, out _Number);
        }

        public void Reset_Position()
        {
            GDEDataManager.ResetToDefault(_key, PositionKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(PositionKey, out _Position);
        }

        public void Reset_Speed()
        {
            GDEDataManager.ResetToDefault(_key, SpeedKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(SpeedKey, out _Speed);
        }

        public void Reset_TimeWaitingSpwan()
        {
            GDEDataManager.ResetToDefault(_key, TimeWaitingSpwanKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(TimeWaitingSpwanKey, out _TimeWaitingSpwan);
        }

        public void Reset_MaxZombies()
        {
            GDEDataManager.ResetToDefault(_key, MaxZombiesKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(MaxZombiesKey, out _MaxZombies);
        }

        public void ResetAll()
        {
            GDEDataManager.ResetToDefault(_key, IDKey);
            GDEDataManager.ResetToDefault(_key, MissionIDKey);
            GDEDataManager.ResetToDefault(_key, WaveKey);
            GDEDataManager.ResetToDefault(_key, AlertKey);
            GDEDataManager.ResetToDefault(_key, IDZombieKey);
            GDEDataManager.ResetToDefault(_key, NumberKey);
            GDEDataManager.ResetToDefault(_key, PositionKey);
            GDEDataManager.ResetToDefault(_key, SpeedKey);
            GDEDataManager.ResetToDefault(_key, TimeWaitingSpwanKey);
            GDEDataManager.ResetToDefault(_key, MaxZombiesKey);


            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
