// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEWaveData : IGDEData
    {
        private static string IdKey = "Id";
		private int _Id;
        public int Id
        {
            get { return _Id; }
            set {
                if (_Id != value)
                {
                    _Id = value;
                    GDEDataManager.SetInt(_key+"_"+IdKey, _Id);
                }
            }
        }

        private static string WaveItemsKey = "WaveItems";
		public List<GDEWaveItemData>      WaveItems;
		public void Set_WaveItems()
        {
	        GDEDataManager.SetCustomList(_key+"_"+WaveItemsKey, WaveItems);
		}
		

        public GDEWaveData()
		{
			_key = string.Empty;
		}

		public GDEWaveData(string key)
		{
			_key = key;
		}
		
        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetInt(IdKey, out _Id);

                dict.TryGetCustomList(WaveItemsKey, out WaveItems);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _Id = GDEDataManager.GetInt(_key+"_"+IdKey, _Id);

            WaveItems = GDEDataManager.GetCustomList(_key+"_"+WaveItemsKey, WaveItems);
         }

        public void Reset_Id()
        {
            GDEDataManager.ResetToDefault(_key, IdKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(IdKey, out _Id);
        }

        public void Reset_WaveItems()
		{
			GDEDataManager.ResetToDefault(_key, WaveItemsKey);

			Dictionary<string, object> dict;
			GDEDataManager.Get(_key, out dict);

			dict.TryGetCustomList(WaveItemsKey, out WaveItems);
			WaveItems = GDEDataManager.GetCustomList(_key+"_"+WaveItemsKey, WaveItems);

			WaveItems.ForEach(x => x.ResetAll());
		}

        public void ResetAll()
        {
            GDEDataManager.ResetToDefault(_key, IdKey);
            GDEDataManager.ResetToDefault(_key, WaveItemsKey);

            Reset_WaveItems();

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
